# Generated by Django 3.1.5 on 2021-02-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0002_auto_20210222_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='endTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='startTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
