# Generated by Django 3.1.5 on 2021-02-25 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0004_doctor_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
