# Generated by Django 3.1.5 on 2021-02-25 10:21

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('medicalapp', '0005_auto_20210225_0713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='link',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='endTime',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='startTime',
        ),
        migrations.AddField(
            model_name='hospital',
            name='image',
            field=django_resized.forms.ResizedImageField(crop=None, default='hospital.svg', force_format=None, keep_meta=True, quality=0, size=[300, 300], upload_to='hospital_images'),
        ),
    ]
